image: docker:latest

variables:
    PROJECT_NAME: 'sczone-crawler'

stages:
    - build

docker-build:
    stage: build
    image: docker:latest
    script:
        - docker build -t $PROJECT_NAME:$CI_COMMIT_REF_NAME -t $PROJECT_NAME:latest .
        # 删除已经在运行的容器
        - if [ $(docker ps -aq --filter name=$PROJECT_NAME) ]; then docker rm -f $PROJECT_NAME;fi
        # 通过镜像启动容器，并把本机8000端口映射到容器8000端口
        - docker run -d -e TZ=Asia/Shanghai --name $PROJECT_NAME $PROJECT_NAME:latest
        - docker image prune -a --filter "until=24h"
    only:
        - tags
