image: docker:latest

variables:
    PROJECT_NAME: 'sczone-crawler'

stages:
    - build

docker-build:
    stage: build
    image: docker:latest
    script:
        - docker build -t $PROJECT_NAME:latest .
        - if [ $(docker ps -aq --filter name=$PROJECT_NAME) ]; then docker rm -f $PROJECT_NAME;fi
        - docker run -d -e TZ=Asia/Shanghai --name $PROJECT_NAME $PROJECT_NAME:latest
    only:
        - tags
