image: docker:latest

variables:
    PROJECT_NAME: 'sczone-crawler'

stages:
    - build

docker-build:
    stage: build
    image: docker:latest
    script:
        - docker build -t $PROJECT_NAME:latest .
        - if [ $(docker ps -aq --filter name=${PROJECT_NAME}_1) ]; then docker rm -f ${PROJECT_NAME}_1;fi
        - docker run -d -e TZ=Asia/Shanghai -e REGION_NO=1 --name ${PROJECT_NAME}_1 -v /volume3/docker/sczone-crawler/config.ini:/app/config.ini -v /volume3/docker/sczone-crawler/logs:/app/logs $PROJECT_NAME:latest
        - if [ $(docker ps -aq --filter name=${PROJECT_NAME}_2) ]; then docker rm -f ${PROJECT_NAME}_2;fi
        - docker run -d -e TZ=Asia/Shanghai -e REGION_NO=2 --name ${PROJECT_NAME}_2 -v /volume3/docker/sczone-crawler/config.ini:/app/config.ini -v /volume3/docker/sczone-crawler/logs:/app/logs $PROJECT_NAME:latest
        - if [ $(docker ps -aq --filter name=${PROJECT_NAME}_3) ]; then docker rm -f ${PROJECT_NAME}_3;fi
        - docker run -d -e TZ=Asia/Shanghai -e REGION_NO=3 --name ${PROJECT_NAME}_3 -v /volume3/docker/sczone-crawler/config.ini:/app/config.ini -v /volume3/docker/sczone-crawler/logs:/app/logs $PROJECT_NAME:latest
        - if [ $(docker ps -aq --filter name=${PROJECT_NAME}_5) ]; then docker rm -f ${PROJECT_NAME}_5;fi
        - docker run -d -e TZ=Asia/Shanghai -e REGION_NO=5 --name ${PROJECT_NAME}_5 -v /volume3/docker/sczone-crawler/config.ini:/app/config.ini -v /volume3/docker/sczone-crawler/logs:/app/logs $PROJECT_NAME:latest
    only:
        - tags
